name: pac20242
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  provider: ^6.1.2
  intl: ^0.20.1
  printing: ^5.13.4
  pdf: ^3.11.1
  signature: ^5.5.0
  image: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bibi.png
    - assets/images/Decoration1.png
    - assets/images/Decoration2.png
    - assets/images/Decoration3.png
    - assets/images/Decoration4.png
  fonts:
    - family: ProtestRiot
      fonts:
        - asset: assets/fonts/ProtestRiot-Regular.ttf
