name: pac20242
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bibi.png
    - assets/images/Decoration1.png
    - assets/images/Decoration2.png
    - assets/images/Decoration3.png
    - assets/images/Decoration4.png
  fonts:
    - family: ProtestRiot
      fonts:
        - asset: assets/fonts/ProtestRiot-Regular.ttf
